sudo: false
language: java
jdk:
  - oraclejdk7
install: 
  - wget --quiet --output-document=/tmp/ceylon.zip $CEYLON
  - unzip /tmp/ceylon.zip
  - export PATH=$PATH:$PWD/ceylon-1.3.2/bin/
before_script: 
  - ceylon compile
script: 
  - ceylon test $TEST_MODULE
env:
  global:
    - CEYLON="https://downloads.ceylon-lang.org/cli/ceylon-1.3.2.zip"
    - TEST_MODULE="test.net.gyokuro.core"
